In [2]:
for name in dir():
    if not name.startswith("_") and name not in ["In", "Out", "get_ipython", "exit", "quit"]:
        del globals()[name]


---
---

In [3]:
# import pandas as pd
# data = pd.read_csv(r"C:\Users\USER\Downloads\Churn_Modelling.csv").drop(columns=['RowNumber', 'CustomerId', 'Surname'])
# data = pd.get_dummies(data, columns=['Geography', 'Gender'], drop_first=True, dtype=int)

In [4]:
# exited_1 = data[data['Exited']==1].reset_index(drop=True)
# exited_0 = data[data['Exited']==0].sample(n=2963, random_state=42).reset_index(drop=True)
# data_5000 = pd.concat([exited_0, exited_1], axis=0)

In [5]:
# data = data_5000.drop(columns=['Exited']) #要跑GAP, no_Y就這樣存
# data_5000.to_csv('churn.csv', sep='\t', encoding='utf-8', index=False) #整筆這樣存, 後續再改data儲存後跑GAP才不會有問題

---
---

In [6]:
import pandas as pd

churn = pd.read_csv(r"C:\Users\No\Documents\GitHub\psychic-spoon\DataSet\churn.csv", sep='\t')
churn['filename'] = [f'{i}' for i in range(1, 5001)]
churn['filename'] = churn['filename'].astype(int)
# banknote = banknote.drop(columns=['class'])
# churn.to_csv('churn.csv', sep='\t', encoding='utf-8', index=False) 
gap_churn_order = pd.read_csv(r"C:\Users\No\Documents\GitHub\psychic-spoon\DataSet\gap_churn_歐式.txt", sep='\t')
raw = '8  1  0  8  1  0  6  7  7  1  2  6  0  1  3  3  6  7  7  1  0  0  0  7  0  7  0  6  3  6  7  1  0  3  1  4  1  0  1  7  3  7  7  4  3  4  8  1  3  0  0  1  1  6  7  4  0  1  8  1  0  7  1  0  7  6  1  1  7  1  1  4  6  5  0  3  0  0  6  7  0  4  0  1  4  1  1  6  6  0  0  0  1  1  8  0  1  1  6  2  6  3  3  4  0  3  3  7  3  1  8  7  7  7  0  2  8  3  7  6  4  8  0  1  7  8  8  6  6  1  0  3  6  0  6  7  1  6  5  4  7  6  1  1  4  7  1  0  2  1  1  3  0  3  7  6  2  3  3  7  1  1  4  1  1  6  3  3  8  3  1  6  6  7  0  0  6  3  6  6  6  8  7  8  6  8  7  0  0  6  1  1  0  6  0  7  7  7  7  4  7  0  1  8  5  8  6  0  4  3  0  3  1  0  0  3  4  0  1  8  6  1  0  7  6  1  6  3  3  3  3  4  4  3  7  3  3  6  0  1  8  8  8  7  3  3  7  3  3  7  8  1  1  3  3  7  1  1  2  8  4  0  3  8  7  8  0  3  7  7  3  7  6  6  0  8  0  8  6  1  3  7  3  8  8  7  1  6  0  0  1  8  2  3  1  0  1  1  0  7  1  7  1  1  6  1  5  3  4  0  0  6  1  6  0  3  1  6  7  6  3  3  0  0  7  0  7  6  3  1  6  7  6  7  6  1  0  0  6  7  3  2  0  0  0  7  8  3  6  1  6  6  3  8  8  7  8  5  1  1  3  6  6  1  3  3  7  7  5  1  0  7  6  0  6  5  6  7  1  8  8  8  0  6  0  7  0  0  1  4  0  7  4  7  3  8  0  3  8  8  1  0  8  3  1  3  7  6  8  8  1  1  1  1  4  2  7  0  0  0  6  6  3  7  1  7  1  1  4  1  0  0  6  7  1  0  0  3  3  6  1  7  3  1  6  3  1  7  0  0  3  7  6  0  0  0  7  1  3  0  1  3  1  0  3  7  4  6  7  3  3  0  2  3  3  4  1  2  7  1  1  8  1  6  0  7  1  4  0  0  0  1  1  3  6  2  8  3  6  6  0  8  3  0  8  2  8  0  0  6  1  6  3  3  0  8  1  0  3  3  0  7  0  8  3  7  0  6  7  8  4  3  1  7  7  1  6  8  7  7  3  1  0  2  7  1  1  0  0  1  7  1  7  7  4  1  6  4  3  7  3  6  3  7  0  3  0  0  1  7  7  3  3  0  7  1  4  8  7  0  6  6  7  7  8  7  7  1  1  4  0  8  4  1  7  3  7  7  3  8  3  1  0  6  0  3  5  0  0  1  1  4  4  4  6  0  6  7  3  7  0  8  7  1  0  7  4  1  8  8  0  0  8  3  1  1  8  8  7  1  1  1  0  3  0  1  6  0  2  6  3  7  3  7  8  0  1  1  7  7  0  3  3  2  7  1  0  3  3  4  1  0  7  3  8  1  3  0  7  2  0  0  3  2  6  4  1  1  8  2  7  1  1  3  0  3  7  0  0  7  6  0  7  0  4  6  0  8  3  8  8  1  1  8  0  1  7  0  0  8  7  3  7  1  8  7  0  3  1  8  1  0  1  3  8  0  4  7  7  8  3  3  0  1  0  0  8  7  6  1  3  7  3  3  6  4  0  6  7  8  1  4  7  4  5  0  8  3  7  1  1  3  0  4  0  0  0  3  1  3  0  0  7  8  8  3  1  1  6  6  6  6  1  0  1  7  7  3  3  0  7  2  3  1  7  6  8  0  8  8  6  7  1  1  7  6  6  1  0  3  8  0  3  6  8  7  4  2  6  0  2  7  6  6  3  0  0  7  1  1  1  0  0  1  8  2  1  1  6  2  6  7  0  7  0  1  0  0  8  7  0  6  0  7  1  1  8  7  3  4  3  3  6  3  1  7  1  8  8  3  0  7  7  0  7  0  6  0  6  0  3  7  3  1  3  1  1  3  6  1  7  5  7  3  7  7  1  1  1  6  0  6  0  3  0  4  4  0  0  6  1  3  6  8  1  3  4  1  7  6  0  7  8  1  0  7  0  7  8  6  0  7  1  8  1  8  1  7  8  6  0  6  6  8  6  3  5  7  0  1  1  6  3  1  1  3  1  1  8  1  8  7  0  7  0  3  6  7  0  0  6  0  3  7  3  1  7  1  8  8  3  0  1  0  0  0  6  6  7  3  1  6  4  7  3  6  7  0  7  2  0  7  3  4  3  7  7  0  6  8  1  1  1  1  8  1  0  3  1  8  6  1  3  6  1  6  0  3  3  3  4  6  0  3  0  8  1  1  7  0  1  6  0  3  4  6  0  3  7  0  3  8  7  6  8  0  0  3  8  3  0  7  6  0  4  3  0  6  5  8  0  7  0  1  0  3  6  7  1  1  7  0  3  1  7  0  3  1  0  1  3  0  7  3  1  6  3  8  8  0  3  6  3  7  0  3  8  6  6  7  3  3  7  0  0  5  4  7  7  3  6  3  7  1  3  3  2  3  3  3  0  1  0  1  0  1  1  0  1  3  8  6  8  7  3  1  3  3  3  7  0  7  7  0  7  4  3  1  0  7  1  6  4  3  7  0  0  0  0  2  0  0  1  4  7  7  1  7  6  4  1  8  4  0  1  3  1  3  6  3  5  0  1  0  1  4  7  7  1  1  0  7  7  1  3  6  1  0  0  0  0  0  8  6  1  1  7  8  0  1  3  8  8  4  0  0  3  7  3  4  1  7  6  0  7  7  7  3  3  0  0  3  8  8  8  0  1  3  1  6  1  3  3  3  3  7  3  1  7  3  6  1  6  8  3  3  6  1  7  0  7  2  3  7  4  1  3  8  0  6  0  3  7  7  2  0  1  6  3  4  0  7  1  1  4  0  8  1  8  0  3  1  0  0  0  6  7  8  0  6  0  7  3  0  0  7  1  6  3  3  8  4  2  1  7  0  5  0  1  8  6  4  6  7  0  6  0  0  0  3  1  1  7  3  6  3  6  1  0  7  3  0  7  0  0  3  8  7  3  6  3  3  1  7  1  1  3  7  7  1  8  8  1  1  6  7  6  1  1  3  0  3  1  7  7  1  7  1  4  0  8  1  7  6  7  6  4  3  6  6  0  7  6  6  8  1  0  6  0  7  1  7  0  1  8  7  8  3  6  1  3  6  6  7  3  7  6  1  0  1  1  1  7  6  1  1  7  2  8  3  7  6  7  1  3  8  0  0  1  7  1  1  0  6  0  8  1  5  8  1  2  0  6  0  3  7  0  4  0  1  0  1  4  7  0  0  3  5  3  6  0  2  1  0  3  1  7  2  3  1  8  0  6  0  6  0  0  1  4  8  0  0  6  0  6  0  6  1  7  8  3  0  8  3  3  0  0  1  6  1  7  5  3  1  6  3  1  4  1  0  7  3  1  0  7  0  7  6  0  0  1  0  6  8  7  8  1  8  4  7  0  1  3  7  6  2  6  6  8  1  0  3  5  2  8  3  0  8  7  3  0  8  7  8  3  4  6  4  0  6  1  7  0  7  7  1  6  3  1  0  1  1  2  1  0  0  7  7  0  1  6  7  7  7  0  8  7  1  7  1  0  1  8  3  7  0  7  1  1  7  7  8  7  3  6  0  1  6  0  7  1  0  1  8  7  7  2  1  7  1  0  0  4  6  6  7  0  8  8  8  0  1  3  3  1  0  4  0  7  3  0  4  8  0  1  3  1  6  4  3  4  0  0  1  0  0  1  0  1  7  7  3  8  1  3  4  6  0  1  8  4  6  1  0  1  3  0  3  0  0  1  6  0  7  6  1  7  0  1  1  1  3  5  1  3  1  1  3  1  0  3  0  8  7  7  6  4  1  1  4  3  3  8  7  0  0  7  1  4  7  3  0  6  4  3  6  1  1  4  3  2  3  1  1  3  1  6  7  3  6  6  0  6  0  6  5  8  8  0  7  3  3  7  4  4  7  3  7  3  7  1  0  7  3  4  6  8  3  7  8  3  3  7  0  0  3  3  1  3  0  2  3  1  6  7  0  7  6  3  0  7  4  2  0  1  0  0  3  5  0  6  4  0  6  2  7  1  1  0  0  1  6  8  0  8  8  6  1  0  0  7  7  0  1  3  7  8  2  1  1  3  0  1  7  2  8  3  1  3  0  1  1  7  6  6  3  1  0  3  0  3  1  1  0  3  8  7  3  7  8  3  3  0  7  7  1  3  7  3  1  0  3  5  7  3  1  1  5  3  0  0  6  7  0  6  0  7  6  0  0  1  0  3  7  3  0  7  1  6  0  7  3  7  1  6  6  6  1  1  1  7  7  3  7  3  8  0  3  1  3  1  0  7  1  1  6  6  7  1  3  7  0  8  0  7  0  1  0  5  1  1  1  8  2  0  1  1  0  6  6  7  8  6  6  1  7  1  7  8  6  8  1  0  8  6  2  3  6  3  3  0  1  7  7  7  0  4  3  0  7  1  1  6  7  2  5  1  0  8  7  1  3  3  4  8  1  6  4  6  6  7  6  6  0  7  7  7  1  0  0  1  8  1  1  0  3  1  1  7  3  1  3  4  6  0  8  1  7  1  3  3  3  1  5  3  1  7  7  6  3  3  0  1  1  1  3  7  2  7  7  0  8  6  1  1  3  1  3  7  1  6  8  7  0  1  0  7  7  7  7  6  6  1  0  3  7  4  1  7  0  4  7  6  1  1  0  8  1  1  1  7  3  1  8  1  3  0  7  1  0  1  6  0  1  6  3  4  0  8  4  1  6  7  7  0  1  7  0  1  3  6  7  3  1  6  4  1  1  1  3  3  4  0  8  7  4  1  2  4  1  1  1  8  1  6  4  1  1  3  0  0  0  7  1  0  8  0  4  7  7  0  7  3  1  0  6  0  0  1  5  4  3  3  1  6  7  0  8  4  8  6  3  8  1  0  8  8  1  8  7  7  8  0  2  1  0  6  3  1  7  6  3  6  1  1  3  4  8  1  0  1  1  7  0  0  1  6  6  6  1  6  7  6  7  0  0  0  7  2  3  8  3  1  7  8  6  3  7  7  7  1  7  7  3  1  8  7  8  0  3  7  6  0  6  3  8  3  7  1  7  1  6  0  1  8  3  7  7  3  4  7  0  3  8  0  3  3  3  1  2  3  0  6  8  0  4  0  0  6  7  1  3  0  3  2  3  3  3  1  1  3  0  0  1  3  7  7  1  3  4  8  4  1  0  3  3  7  1  3  3  7  3  0  1  3  0  5  6  7  1  1  1  3  1  0  7  0  1  0  7  0  1  3  1  7  0  6  1  1  0  1  1  0  8  7  0  0  7  7  7  0  5  0  1  6  1  6  0  0  1  0  7  1  6  6  1  6  0  0  4  1  6  1  0  5  1  1  6  3  3  8  1  0  2  3  0  0  0  6  7  7  2  7  1  1  3  4  3  8  6  8  1  7  4  1  0  1  0  7  0  0  1  1  3  1  0  3  0  0  7  3  6  1  6  3  8  7  0  0  3  1  1  1  7  0  0  0  6  7  6  3  0  7  1  6  7  4  3  1  8  6  1  1  7  8  6  0  0  1  1  8  2  7  0  1  0  1  0  0  1  3  0  1  2  7  7  3  8  7  0  1  1  1  1  1  3  0  6  3  1  1  1  6  7  0  6  8  8  6  3  3  1  1  0  3  3  0  1  8  2  6  7  4  3  1  4  0  8  8  4  8  7  1  1  3  0  6  8  7  8  1  8  7  0  8  0  7  4  0  1  7  6  3  4  0  3  7  8  3  8  2  3  7  6  0  7  0  1  8  7  3  3  1  0  4  8  8  1  6  6  7  0  3  8  7  1  7  8  1  7  8  1  0  1  7  0  6  6  0  1  0  0  1  8  0  0  3  0  7  3  0  1  8  6  7  8  1  7  1  0  6  0  8  1  6  0  1  0  0  1  7  4  7  0  1  0  4  1  7  6  6  4  6  1  3  1  1  6  0  3  0  1  0  1  7  3  6  3  4  2  5  1  6  6  6  7  3  1  6  0  0  0  1  2  7  1  6  0  7  4  6  7  3  8  8  0  4  2  8  8  6  7  1  3  4  8  7  7  6  4  3  7  6  2  8  3  1  8  6  6  3  6  1  8  1  3  7  1  0  0  0  7  6  8  3  3  0  0  1  1  0  3  8  3  0  0  6  0  1  7  0  3  3  3  3  1  0  0  0  1  3  4  5  7  1  3  1  0  0  1  8  6  6  1  0  1  3  1  7  1  3  6  3  1  0  1  3  1  1  7  7  3  8  0  1  0  7  3  8  3  6  4  3  0  6  6  3  1  6  0  3  6  4  6  3  1  7  8  0  8  8  8  0  5  4  7  3  3  7  6  6  3  4  7  6  3  2  0  0  0  3  1  7  6  1  6  5  7  6  1  0  8  6  4  0  3  7  3  1  7  1  1  8  0  7  0  0  6  4  4  7  0  3  1  8  0  7  0  0  3  0  7  8  1  1  3  8  3  8  0  1  8  0  3  7  7  1  0  1  0  3  8  7  0  7  1  7  4  1  6  8  1  1  3  6  0  1  3  1  1  0  5  3  1  1  7  6  3  4  3  7  0  1  3  6  3  6  4  6  3  1  7  6  0  7  7  7  3  0  0  3  6  6  7  7  6  3  1  3  0  7  1  0  0  3  7  2  6  7  1  3  1  3  0  0  0  1  3  7  1  3  3  1  7  0  3  6  0  7  3  1  1  7  7  8  3  3  1  3  7  7  1  3  1  0  3  7  0  0  7  7  6  7  6  2  3  3  8  6  3  7  0  8  1  6  6  5  3  8  3  7  8  7  7  6  6  3  8  3  3  0  3  0  7  0  4  8  1  6  5  3  1  3  8  2  1  3  6  6  1  0  1  0  8  3  6  3  7  3  3  0  1  0  6  1  3  4  7  6  3  4  3  7  2  7  3  4  7  3  4  5  6  0  3  6  6  8  3  6  7  3  3  7  7  3  6  1  8  8  7  1  8  1  7  8  0  2  5  2  8  3  1  0  4  1  3  7  8  0  1  7  1  1  0  0  8  0  0  3  4  7  7  7  8  3  7  7  2  3  0  0  6  3  5  7  1  0  3  6  4  3  1  1  3  5  6  0  8  6  1  8  7  2  3  8  6  6  8  6  0  1  7  6  7  3  1  7  3  5  0  7  8  7  6  7  7  1  0  1  0  0  3  7  4  7  4  8  7  0  8  5  3  3  7  4  4  0  0  0  3  3  1  0  7  5  8  3  3  1  5  8  3  7  6  1  4  3  2  3  1  3  1  8  7  0  7  7  3  3  0  3  6  8  3  4  8  3  0  7  6  0  7  3  6  0  4  2  3  8  8  6  6  7  6  3  6  3  7  3  0  3  3  7  0  4  1  8  7  6  6  6  7  7  6  1  8  8  1  8  0  0  4  7  0  6  8  0  7  7  7  7  8  1  3  3  4  0  6  3  7  6  3  7  7  0  4  8  3  0  2  3  6  6  7  3  8  0  6  7  6  3  7  7  7  8  6  7  7  5  7  7  0  0  3  1  7  7  1  1  3  3  8  1  1  6  2  0  3  0  5  0  6  0  1  6  0  7  4  7  4  2  1  8  3  8  0  7  6  7  4  3  1  3  0  3  2  3  8  3  8  7  8  0  7  3  4  8  1  7  6  7  0  3  7  6  3  6  8  4  3  8  4  3  1  6  0  7  3  1  8  8  3  7  3  8  3  7  3  7  7  1  3  2  6  7  3  4  8  3  7  6  0  1  3  8  0  3  7  7  0  7  7  0  4  3  7  7  5  0  8  6  6  7  0  1  8  6  1  6  6  0  7  8  8  7  0  1  1  0  1  8  3  3  6  8  3  3  0  7  7  1  7  0  4  7  3  8  6  3  2  7  7  6  1  3  1  3  0  3  3  7  8  7  8  3  6  0  2  0  7  3  6  6  8  6  7  2  6  7  1  1  6  0  7  8  0  3  3  7  6  7  6  3  7  7  3  0  8  6  8  0  1  1  6  7  0  6  6  3  1  6  6  3  6  0  6  6  1  7  8  7  0  7  7  6  7  0  7  4  0  6  3  3  8  0  3  2  7  1  0  0  3  7  7  7  8  3  8  3  7  1  4  1  7  7  7  7  0  0  6  1  3  1  7  1  1  0  3  7  1  0  6  7  1  8  1  1  0  7  1  5  6  3  3  3  6  7  0  3  0  3  3  3  6  3  3  1  3  6  1  7  8  4  7  2  6  4  4  4  1  8  4  6  5  6  1  3  3  1  0  7  7  4  0  1  6  7  1  3  6  1  6  7  7  8  3  1  7  7  0  2  7  7  3  0  1  3  8  6  3  3  7  8  1  7  1  3  8  0  6  3  0  3  8  7  1  1  8  1  6  4  3  3  8  5  6  1  7  3  7  7  3  7  1  3  3  7  3  6  7  3  1  7  3  7  8  6  3  3  7  7  1  0  0  6  7  3  7  3  6  3  1  7  8  7  3  6  7  3  8  1  8  1  1  1  0  6  6  2  6  0  3  3  3  6  8  3  3  0  0  3  6  3  1  3  8  6  1  6  8  3  0  1  0  1  3  8  3  1  3  3  6  1  8  1  4  0  1  3  3  7  0  0  7  1  6  4  0  7  0  1  3  3  8  7  6  0  8  7  1  0  8  6  7  3  6  0  7  6  3  7  0  6  4  7  7  2  0  3  3  0  7  7  7  8  3  0  3  2  0  7  7  1  1  3  4  7  5  8  0  7  0  7  3  7  7  2  3  7  6  1  0  6  1  6  7  0  8  8  8  1  0  3  6  7  6  7  1  0  3  0  0  6  8  3  7  7  3  6  6  7  0  3  3  0  3  1  3  3  1  8  7  6  0  6  0  7  6  5  1  1  0  3  1  7  3  7  0  1  1  7  6  6  6  7  8  2  3  8  1  7  3  8  8  7  0  3  6  5  1  6  5  7  3  6  7  6  3  1  6  3  7  7  4  0  6  7  7  3  8  3  8  4  7  7  6  3  0  4  1  6  6  8  6  5  8  7  0  7  6  0  0  1  7  6  3  0  8  7  3  1  7  3  1  3  6  0  6  7  1  3  7  1  8  7  0  3  3  3  4  7  6  6  1  8  3  8  0  6  7  1  6  3  1  6  8  4  6  3  7  4  8  0  8  3  8  3  1  1  3  8  8  7  7  8  7  8  6  6  8  3  8  6  7  7  3  4  7  6  3  2  6  3  6  1  8  3  8  7  0  1  6  3  7  6  6  1  2  3  7  1  0  8  7  0  2  3  4  0  0  7  8  6  7  3  7  7  0  8  4  3  8  0  4  6  0  0  6  7  7  7  1  3  7  8  0  4  1  0  6  7  1  2  6  2  1  3  3  8  7  6  4  5  3  0  1  7  3  7  6  0  3  3  7  1  3  3  3  7  1  0  6  3  0  3  7  0  7  7  6  1  7  7  7  8  0  4  3  8  7  3  6  1  6  6  1  3  1  0  3  8  7  1  7  6  2  0  3  6  4  6  3  3  7  8  3  3  3  6  4  6  3  0  2  7  3  8  0  8  8  0  6  6  7  6  7  1  6  1  8  0  7  6  7  0  7  0  1  7  0  3  3  8  1  2  3  0  8  3  3  3  8  7  0  8  4  0  4  7  5  3  6  4  7  7  4  7  3  3  1  8  6  3  3  6  3  2  8  1  7  6  1  6  3  6  6  6  0  1  0  3  1  7  6  6  7  7  0  2  0  0  1  6  1  8  6  6  0  3  8  3  1  0  6  7  3  2  1  1  8  7  7  3  2  0  7  1  8  3  8  8  0  6  8  2  0  8  8  6  8  0  8  7  2  4  8  7  7  4  0  3  3  6  7  0  7  3  7  2  3  7  1  1  3  8  8  6  3  2  7  3  3  7  8  6  7  3  6  6  3  3  7  0  6  7  7  0  3  8  4  3  3  3  1  2  7  6  4  8  1  6  0  3  4  6  1  3  6  7  3  3  3  8  2  7  7  0  1  3  8  7  0  5  7  4  7  3  3  5  0  0  3  3  8  3  3  6  6  7  6  7  7  3  1  3  6  4  1  8  7  3  3  3  7  7  6  1  2  8  0  1  6  7  3  6  1  8  1  7  7  1  8  8  3  6  0  2  4  0  1  6  6  7  1  6  7  6  2  3  1  8  8  0  3  3  3  8  7  7  1  4  6  2  6  3  7  8  6  7  6  3  1  3  0  7  7  7  7  7  3  8  0  7  6  7  6  4  6  3  3  6  1  0  7  6  3  1  8  0  6  6  3  2  8  1  1  0  6  8  0  0  2  7  8  3  8  7  3  6  8  8  7  6  7  3  5  1  1  6  1  7  4  8  3  6  4  7  6  6  3  1  6  3  1  5  7  8  0  6  1  3  4  3  6  7  3  3  3  6  3  8  3  0  1  6  0  0  7  7  8  2  3  6  6  1  3  6  0  8  3  7  1  1  3  1  3  6  3  7  3  3  3  0  7  0  7  7  7  3  6  1  4  7  1  1  6  3  6  6  3  3  1  8  8  7  1  7  0  3  3  7  6  7  0  7  7  0  7  0  7  7  3  6  7  7  8  0  8  6  3  7  0  0  4  3  6  0  7  7  8  0  7  1  7  8  8  3  7  8  7  3  3  3  0  0  3  3  1  7  6  7  5  7  0  0  6  4  0  3  2  7  8  8  0  3  1  0  6  8  3  0  8  5  1  5  4  3  8  7  3  0  8  1  5  6  4  2  8  7  0  3  3  6  2  7  7  6  1  7  0  7  0  3  3  6  3  0  0  6  3  8  5  3  4  7  6  3  3  0  6  3  0  7  1  4  5  3  0  6  1  7  3  4  3  7  0  4  3  8  6  6  3  7  5  3  6  3  7  0  0  3  3  0  1  8  3  0  8  4  3  7  3  3  0  8  3  3  3  3  6  7  6  6  3  6  1  1  3  6  1  8  0  1  6  8  1  7  0  7  7  1  7  3  1  3  0  1  1  6  1  0  7  7  7  7  6  4  3  3  7  0  3  3  1  8  8  8  0  1  8  3  8  7  0  0  6  6  1  3  8  7  0  6  8  2  8  6  7  7  1  0  7  7  1  8  6  3  7  7  3  8  7  0  3  8  3  3  3  3  2  8  6  7  8  3  8  6  3  3  7  3  1  8  1  7  8  7  3  3  7  4  7  7  1  6  3  7  4  1  7'
raw_list = [int(i) for i in raw.split()]
gap_churn_order['gap_cluster'] = raw_list
gap_churn_order['filename'] = gap_churn_order['UNIQID'].str.lstrip('r').astype('int')+1
gap_churn_order = gap_churn_order.drop(columns=['UNIQID'])

churn_merged = pd.merge(churn, gap_churn_order[['gap_cluster', 'filename']], on='filename').drop(columns=['filename'])


In [7]:
churn_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   CreditScore        5000 non-null   int64  
 1   Age                5000 non-null   int64  
 2   Tenure             5000 non-null   int64  
 3   Balance            5000 non-null   float64
 4   NumOfProducts      5000 non-null   int64  
 5   HasCrCard          5000 non-null   int64  
 6   IsActiveMember     5000 non-null   int64  
 7   EstimatedSalary    5000 non-null   float64
 8   Exited             5000 non-null   int64  
 9   Geography_Germany  5000 non-null   int64  
 10  Geography_Spain    5000 non-null   int64  
 11  Gender_Male        5000 non-null   int64  
 12  gap_cluster        5000 non-null   int64  
dtypes: float64(2), int64(11)
memory usage: 507.9 KB


In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, confusion_matrix

# X = 特徵, y = 目標
X = churn_merged.drop(columns=['Exited'])
y = churn_merged['Exited']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [9]:
# === 1) Naive ===
dc = DummyClassifier(strategy='prior', random_state=42)
model2 = dc.fit(X_train, y_train)
y_pred2 = model2.predict(X_test)
print("\n=== Naive ===")
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred2))
print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred2, digits=4))


=== Naive ===
=== Confusion Matrix ===
[[900   0]
 [600   0]]

=== Classification Report ===
              precision    recall  f1-score   support

           0     0.6000    1.0000    0.7500       900
           1     0.0000    0.0000    0.0000       600

    accuracy                         0.6000      1500
   macro avg     0.3000    0.5000    0.3750      1500
weighted avg     0.3600    0.6000    0.4500      1500



c:\Users\No\anaconda3\envs\Laptop_20250527\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\No\anaconda3\envs\Laptop_20250527\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\No\anaconda3\envs\Laptop_20250527\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is",

In [10]:
# === 2) Linear SVC ===
lsvc = LinearSVC(random_state=42, max_iter=1000, class_weight='balanced')
model3 = lsvc.fit(X_train, y_train)
y_pred3 = model3.predict(X_test)
print("\n=== Linear SVC ===")
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred3))
print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred3, digits=4))


=== Linear SVC ===
=== Confusion Matrix ===
[[576 324]
 [181 419]]

=== Classification Report ===
              precision    recall  f1-score   support

           0     0.7609    0.6400    0.6952       900
           1     0.5639    0.6983    0.6240       600

    accuracy                         0.6633      1500
   macro avg     0.6624    0.6692    0.6596      1500
weighted avg     0.6821    0.6633    0.6667      1500



In [11]:
# === 3) Logistic Regression ===
lr = LogisticRegression(max_iter=100, random_state=42, solver='liblinear', class_weight='balanced')
model4 = lr.fit(X_train, y_train)
y_pred4 = model4.predict(X_test)
print("\n=== Logistic Regression ===")
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred4))
print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred4, digits=4))


=== Logistic Regression ===
=== Confusion Matrix ===
[[589 311]
 [184 416]]

=== Classification Report ===
              precision    recall  f1-score   support

           0     0.7620    0.6544    0.7041       900
           1     0.5722    0.6933    0.6270       600

    accuracy                         0.6700      1500
   macro avg     0.6671    0.6739    0.6656      1500
weighted avg     0.6861    0.6700    0.6733      1500



In [12]:
# === 4) RandomForestClassifier ===
rfc = RandomForestClassifier(n_estimators=100, random_state=42, max_depth=2, max_leaf_nodes=2, n_jobs=-1, class_weight='balanced')
model1 = rfc.fit(X_train, y_train)
y_pred = model1.predict(X_test)
print("\n=== RandomForestClassifier ===")
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred))
print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred, digits=4))


=== RandomForestClassifier ===
=== Confusion Matrix ===
[[693 207]
 [205 395]]

=== Classification Report ===
              precision    recall  f1-score   support

           0     0.7717    0.7700    0.7709       900
           1     0.6561    0.6583    0.6572       600

    accuracy                         0.7253      1500
   macro avg     0.7139    0.7142    0.7140      1500
weighted avg     0.7255    0.7253    0.7254      1500



In [13]:
# === 5) XGBoost ===
xgb = XGBClassifier(n_estimators=100, max_depth=2, max_leaves=2, learning_rate=0.1, random_state=42, n_jobs=-1, eval_metric='logloss', tree_method='hist')
model5 = xgb.fit(X_train, y_train)
y_pred5 = model5.predict(X_test)
print("\n=== XGBoost ===")
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred5))
print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred5, digits=4))


=== XGBoost ===
=== Confusion Matrix ===
[[792 108]
 [222 378]]

=== Classification Report ===
              precision    recall  f1-score   support

           0     0.7811    0.8800    0.8276       900
           1     0.7778    0.6300    0.6961       600

    accuracy                         0.7800      1500
   macro avg     0.7794    0.7550    0.7619      1500
weighted avg     0.7798    0.7800    0.7750      1500



In [14]:
# # === 6) LightGBM ===
lgbm = LGBMClassifier(n_estimators=100, learning_rate=0.1, max_depth=2, num_leaves=2, random_state=42, n_jobs=-1, class_weight='balanced')
model6 = lgbm.fit(X_train, y_train)
y_pred6 = model6.predict(X_test)
print("\n=== LightGBM ===")
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred6))
print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred6, digits=4))

[LightGBM] [Info] Number of positive: 1437, number of negative: 2063
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000390 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 862
[LightGBM] [Info] Number of data points in the train set: 3500, number of used features: 12
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000

=== LightGBM ===
=== Confusion Matrix ===
[[713 187]
 [157 443]]

=== Classification Report ===
              precision    recall  f1-score   support

           0     0.8195    0.7922    0.8056       900
           1     0.7032    0.7383    0.7203       600

    accuracy                         0.7707      1500
   macro avg     0.7614    0.7653    0.7630      1500
weighted avg     0.7730    0.7707    0.7715      1500



---
---

In [15]:
import pandas as pd, numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from sklearn.ensemble import RandomForestClassifier

y_col = 'Exited'
c_col = 'gap_cluster'
X_cols = [c for c in churn_merged.columns if c not in (y_col, c_col)]
y = churn_merged[y_col]
c = churn_merged[c_col]

strat_key = y.astype(str) + '|' + c.astype(str)
X_train, X_test, y_train, y_test, c_train, c_test = train_test_split(churn_merged[X_cols], y, c, test_size=0.3, stratify=strat_key, random_state=42)

labels_all = np.sort(y.unique())
rows = []
confusion_matrix_= {}
classification_report_ = {}
for k in sorted(c_train.unique()):
    train_mask = (c_train == k)
    test_mask = (c_test == k)
    Xk_train, yk_train = X_train[train_mask], y_train[train_mask]
    Xk_test, yk_test = X_test[test_mask], y_test[test_mask]

    if len(yk_train.unique())<2 or len(yk_test)==0:
        rows.append({'cluster':k, 'n_train':len(yk_train), 'n_test':len(yk_test), 'Acc':np.nan, 'F1':np.nan, 'note':'類別不足或無測試樣本'})
        continue

    naive_ = DummyClassifier(strategy='prior', random_state=42)
    naive_.fit(Xk_train, yk_train)
    naive__y_hat = naive_.predict(Xk_test)
    naive__y_proba = naive_.predict_proba(Xk_test)[:,1]
    rows.append({'cluster':k, 'model':'naive', 'n_train':len(yk_train), 'n_test':len(yk_test), 'Acc':accuracy_score(yk_test, naive__y_hat), 'F1':f1_score(yk_test, naive__y_hat, average='macro'), 'AUC':roc_auc_score(yk_test, naive__y_proba)})
    confusion_matrix_[(k, 'naive')] = confusion_matrix(yk_test, naive__y_hat, labels=labels_all)
    classification_report_[(k, 'naive')] = classification_report(yk_test, naive__y_hat)

    lsvm = LinearSVC(random_state=42, max_iter=1000, class_weight='balanced')
    lsvm.fit(Xk_train, yk_train)
    lsvm__y_hat = lsvm.predict(Xk_test)
    lsvm__y_prob = lsvm.decision_function(Xk_test)
    rows.append({'cluster':k, 'model':'lsvm', 'n_train':len(yk_train), 'n_test':len(yk_test), 'Acc':accuracy_score(yk_test, lsvm__y_hat), 'F1':f1_score(yk_test, lsvm__y_hat, average='macro'), 'AUC':roc_auc_score(yk_test, lsvm__y_prob)})
    confusion_matrix_[(k, 'LinearSVC')] = confusion_matrix(yk_test, lsvm__y_hat, labels=labels_all)
    classification_report_[(k, 'LinearSVC')] = classification_report(yk_test, lsvm__y_hat)

    lr = LogisticRegression(max_iter=100, random_state=42, solver='liblinear', class_weight='balanced')
    lr.fit(Xk_train, yk_train)
    lr_y_hat = lr.predict(Xk_test)
    lr__y_proba = lr.predict_proba(Xk_test)[:,1]
    rows.append({'cluster':k, 'model':'lr', 'n_train':len(yk_train), 'n_test':len(yk_test), 'Acc':accuracy_score(yk_test, lr_y_hat), 'F1':f1_score(yk_test, lr_y_hat, average='macro'), 'AUC':roc_auc_score(yk_test, lr__y_proba)})
    confusion_matrix_[(k, 'LogisticRegression')] = confusion_matrix(yk_test, lr_y_hat, labels=labels_all)
    classification_report_[(k, 'LogisticRegression')] = classification_report(yk_test, lr_y_hat)

    rfc = RandomForestClassifier(n_estimators=100, random_state=42, max_depth=2, max_leaf_nodes=2, n_jobs=-1, class_weight='balanced')
    rfc.fit(Xk_train, yk_train)
    rfc_y_hat = rfc.predict(Xk_test)
    rfc__y_proba = rfc.predict_proba(Xk_test)[:,1]
    rows.append({'cluster':k, 'model':'rfc', 'n_train':len(yk_train), 'n_test':len(yk_test), 'Acc':accuracy_score(yk_test, rfc_y_hat), 'F1':f1_score(yk_test, rfc_y_hat, average='macro'), 'AUC':roc_auc_score(yk_test, rfc__y_proba)})
    confusion_matrix_[(k, 'RandomForestClassifier')] = confusion_matrix(yk_test, rfc_y_hat, labels=labels_all)
    classification_report_[(k, 'RandomForestClassifier')] = classification_report(yk_test, rfc_y_hat)

    xgbc = XGBClassifier(n_estimators=100, max_depth=2, max_leaves=2, learning_rate=0.1, random_state=42, n_jobs=-1, eval_metric='logloss', tree_method='hist')
    xgbc.fit(Xk_train, yk_train)
    xgbc_y_hat = xgbc.predict(Xk_test)
    xgbc__y_proba = xgbc.predict_proba(Xk_test)[:,1]
    rows.append({'cluster':k, 'model':'xgbc', 'n_train':len(yk_train), 'n_test':len(yk_test), 'Acc':accuracy_score(yk_test, xgbc_y_hat), 'F1':f1_score(yk_test, xgbc_y_hat, average='macro'), 'AUC':roc_auc_score(yk_test, xgbc__y_proba)})
    confusion_matrix_[(k, 'XGBClassifier')] = confusion_matrix(yk_test, xgbc_y_hat, labels=labels_all)
    classification_report_[(k, 'XGBClassifier')] = classification_report(yk_test, xgbc_y_hat)

    lgbmc = LGBMClassifier(n_estimators=100, learning_rate=0.1, max_depth=2, num_leaves=2, random_state=42, n_jobs=-1, class_weight='balanced', verbose=-1)
    lgbmc.fit(Xk_train, yk_train)
    lgbmc_y_hat = lgbmc.predict(Xk_test)
    lgbmc__y_proba = lgbmc.predict_proba(Xk_test)[:,1]
    rows.append({'cluster':k, 'model':'lgbmc', 'n_train':len(yk_train), 'n_test':len(yk_test), 'Acc':accuracy_score(yk_test, lgbmc_y_hat), 'F1':f1_score(yk_test, lgbmc_y_hat, average='macro'), 'AUC':roc_auc_score(yk_test, lgbmc__y_proba)})
    confusion_matrix_[(k, 'LGBMClassifier')] = confusion_matrix(yk_test, lgbmc_y_hat, labels=labels_all)
    classification_report_[(k, 'LGBMClassifier')] = classification_report(yk_test, lgbmc_y_hat)

report = pd.DataFrame(rows).sort_values(['cluster','model'])
report

c:\Users\No\anaconda3\envs\Laptop_20250527\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\No\anaconda3\envs\Laptop_20250527\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\No\anaconda3\envs\Laptop_20250527\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is",

,cluster,model,n_train,n_test,Acc,F1,AUC
5,0,lgbmc,590,253,0.715415,0.710490,0.830634
2,0,lr,590,253,0.640316,0.638486,0.711022
1,0,lsvm,590,253,0.644269,0.642251,0.710764
0,0,naive,590,253,0.588933,0.370647,0.500000
3,0,rfc,590,253,0.723320,0.718531,0.796819
4,0,xgbc,590,253,0.747036,0.733509,0.837119
11,1,lgbmc,585,252,0.765873,0.760128,0.843683
8,1,lr,585,252,0.642857,0.640593,0.708412
7,1,lsvm,585,252,0.646825,0.644356,0.708868
6,1,naive,585,252,0.591270,0.371571,0.500000


---
---

In [16]:
confusion_matrix_[(2, 'XGBClassifier')]

array([[19,  3],
       [ 6,  8]], dtype=int64)

In [17]:
print(classification_report_[(2, 'XGBClassifier')])

              precision    recall  f1-score   support

           0       0.76      0.86      0.81        22
           1       0.73      0.57      0.64        14

    accuracy                           0.75        36
   macro avg       0.74      0.72      0.72        36
weighted avg       0.75      0.75      0.74        36



In [18]:
print(classification_report_[(5, 'XGBClassifier')])

              precision    recall  f1-score   support

           0       0.75      0.82      0.78        11
           1       0.78      0.70      0.74        10

    accuracy                           0.76        21
   macro avg       0.76      0.76      0.76        21
weighted avg       0.76      0.76      0.76        21



In [19]:
print(classification_report_[(8, 'XGBClassifier')])

              precision    recall  f1-score   support

           0       0.77      0.85      0.81        93
           1       0.68      0.56      0.61        54

    accuracy                           0.74       147
   macro avg       0.72      0.70      0.71       147
weighted avg       0.74      0.74      0.73       147



In [20]:
print(classification_report_[(8, 'LGBMClassifier')])

              precision    recall  f1-score   support

           0       0.78      0.74      0.76        93
           1       0.59      0.63      0.61        54

    accuracy                           0.70       147
   macro avg       0.68      0.69      0.68       147
weighted avg       0.71      0.70      0.70       147



In [21]:
print(classification_report_[(2, 'LinearSVC')])

              precision    recall  f1-score   support

           0       0.76      0.59      0.67        22
           1       0.53      0.71      0.61        14

    accuracy                           0.64        36
   macro avg       0.65      0.65      0.64        36
weighted avg       0.67      0.64      0.64        36

